### PR TITLE
Fix usability of clear all chips button

### LINKED ISSUE #936: chip-set: keyboard-navigation for delete-all button broken
## Current behavior

1. You can tab to the clear-button, but there doesn't seem to be any way to actually activate it. I've tried both \<enter\>  and \<space\>.
image
2. If you don't hover the component when tabbing to the clear-button, it looks a bit broken:
image
3. It's possible to tab to the button when there are no chips selected.
4. When disabled, it's still possible to tab to the button:
image
5. When read-only, it's not only possible to tab to the button, but it also becomes visible when any chip is hovered:
image

(Ignore the issue with the label cutting part of the chips, when disabled or read-only, that's an unrelated problem, and belongs in a separate issue.)

## Expected behavior

1. Pressing <enter> should activate the button.
2. The button should appear correctly when tabbed to, whether or not the component is being hovered.
3. The button should be taken out of the tab-flow when the component has no chips. We should probably use `display:none`, so it's also hidden from assistive tech.
4. Regardless of if the component is empty or has chips, it should not be possible to tab to the button when the component is disabled.
5. Same as for disabled, no tabbing to the button when the component is read-only, and also don't show the button on hover.

## Environment

- **lime-elements** version: v28.1.0 (introduced in #931)
- Framework used: reproducible in docz-app
- Logs:

### PR DESCRIPTION
**Pull request by Kiarokh**
fix #936 

## Review:
- [ ] Commits are [atomic](https://seesparkbox.com/foundry/atomic_commits_with_git)
- [ ] Commits have the correct *type* for the changes made
- [ ] Commits with *breaking changes* are marked as such

### Browsers tested:
(Check any that applies, it's ok to leave boxes unchecked if testing something didn't seem relevant.)

Windows:
- [ ] Chrome
- [ ] Edge
- [ ] Firefox

Linux:
- [ ] Chrome
- [ ] Firefox

macOS:
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

Mobile:
- [ ] Chrome on Android
- [ ] iOS

### CODE REVIEW

File: src/components/chip-set/chip-set.tsx [hunk 1]
```diff
@@ -572,9 +578,11 @@ export class ChipSet {
         return (
             <i
                 onClick={this.handleDeleteAllIconClick}
-                class="mdc-text-field__icon delete-all-icon-button"
+                class="mdc-text-field__icon clear-all-icon-button"
                 tabindex="0"
                 role="button"
+                title={this.clearAllLabel}
+                area-label={this.clearAllLabel}
```
Comment (adrianschmidt) [inline src/components/chip-set/chip-set.tsx:585]:
```suggestion
                aria-label={this.clearAllLabel}
```

File: src/style/mixins.scss [hunk 2]
```diff
@@ -67,3 +67,26 @@
...
+    background: {
+        color: #babac0;
+        repeat: no-repeat;
+        position: center;
+        size: pxToRem(12);
+        image: url("data:image/svg+xml; utf8, <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'><defs/><path fill='rgb(255,255,255)' d='M7.219 5.781L5.78 7.22 14.563 16 5.78 24.781 7.22 26.22 16 17.437l8.781 8.782 1.438-1.438L17.437 16l8.782-8.781L24.78 5.78 16 14.563z'/></svg>");
+    }
+
+    &:hover {
+        background-color: #757580;
```
Comment (adrianschmidt) [inline src/style/mixins.scss:90]: While we're at it, shouldn't we use the new color-palette for these background colours? 🙂

File: src/components/chip-set/chip-set.tsx [hunk 3]
```diff
@@ -82,6 +82,12 @@ export class ChipSet {
     @Prop({ reflectToAttr: true })
     public searchLabel: string;
 
+    /**
+     * Clear all label to display as `title` and `area-label` for icon button that clears all chips
```
Comment (adrianschmidt) [inline src/components/chip-set/chip-set.tsx:86]:
```suggestion
     * Label to display as `title` and `aria-label` for button that clears all chips
```

File: src/components/chip-set/chip-set.tsx [hunk 4]
```diff
@@ -572,9 +578,11 @@ export class ChipSet {
         return (
             <i
```
Comment (adrianschmidt) [inline src/components/chip-set/chip-set.tsx:579]: I think this should be a link. Then there should be no need for the `tabindex="0"`, and it ought to be possible to trigger it by tabbing to it and pressing \<enter\>.

Alternatively, we might want to use a limel-icon-button, but I'm guessing that might be a little too bloated for use here?

File: src/components/chip-set/chip-set.tsx (hunk 1 above)
Comment (Kiarokh) [reply src/components/chip-set/chip-set.tsx:585]: typical me :D

File: src/style/mixins.scss (hunk 2 above)
Comment (Kiarokh) [reply src/style/mixins.scss:90]: I think we will go through these color things later, one by one in each component.

File: src/components/chip-set/chip-set.tsx (hunk 4 above)
Comment (Kiarokh) [reply src/components/chip-set/chip-set.tsx:579]: have you tried to see whether having it as a link would work? Otherwise I'lll test tomorrow ;)

Comment (Kiarokh) [reply src/components/chip-set/chip-set.tsx:579]: @adrianschmidt this didn't work unfortunately. :( maybe for a link to work, we need a URL? donno

**Comment by Kiarokh** [comment]
@adrianschmidt the tabbing behavior seems to be inconsistent. Sometimes it works (specially when the field is "focused" and you're adding or removing chips) But some times it doesn't (like when you tab into the field from outside). We couldn't really figure out how and why.

**Comment by Kiarokh** [comment]
> It's because unless you hover the component, the button is set to `display:none` as soon as the input loses focus.

But we don't want the (x) to show up when the field is not being used (is not focused). However, in some situations as soon as you tab, the field will lose focus. Right now I'm not sure how to fix this problem. Perhaps the easiest way is to constantly show the (x) button as long as `.has-chips` class exists, even if the field is not in focus.

**Comment by adrianschmidt** [comment]
> > It's because unless you hover the component, the button is set to `display:none` as soon as the input loses focus.
> 
> But we don't want the (x) to show up when the field is not being used (is not focused). However, in some situations as soon as you tab, the field will lose focus. Right now I'm not sure how to fix this problem. Perhaps the easiest way is to constantly show the (x) button as long as `.has-chips` class exists, even if the field is not in focus.

Invisible and `display:none` are not the same thing. But I can fix it later. Busy with some other things at the moment, but tell me once you've done what you want and can, and I'll look at the remaining bits.

**Comment by Kiarokh** [comment]
> By "invisible", I didn't mean `visibility:hidden` or any other specific styling, just that there are ways to make something be not possible to see, while still possible to focus. 

No problem Adrian. Using `visibility:hidden` was actually a smart idea, even if you didn't mean it 😄. `https://developer.mozilla.org/en-US/docs/Web/CSS/visibility` they say:
image

Anyhow, I later realized that you can still tab into the (x) even if there are no chips (due to lack of CSS rules), so in the [last fixup commit](https://github.com/Lundalogik/lime-elements/pull/938/commits/7ee6cb3005a85457ce1b3b0bec540ee8373af194), I fixed this. I also found a bug which is hard to explain. The styles caused the (x) to jump up and down so you couldn't really click it. This happened when the first line in the chipset was filled with chips and the `<input>` (where you type in) was placed on the next line. 

Anyhow, it's now fixed by having an absolut position for the (x) which only considers `right` and `top`. (doesn't middle align itself based on the height of the chipset). This fix gives a more pleasing UI as well.

File: src/components/chip-set/chip-set.tsx [hunk 5]
```diff
@@ -82,6 +82,12 @@ export class ChipSet {
     @Prop({ reflectToAttr: true })
     public searchLabel: string;
 
+    /**
+     * Label to display as `title` and `aria-label` for button that clears all chips
+     */
+    @Prop({ reflectToAttr: true })
+    public clearAllLabel: string;
```
Comment (jgroth) [inline src/components/chip-set/chip-set.tsx:89]: Is this to make it translatable or do we want consumers to be able to change the label to something completely different? 

If it's only for translation purposes, I would suggest to remove this for now and just have it in English. We need to discuss how to handle translations in Lime Elements at a broader scope before it becomes unmaintainable. I would prefer if we could solve it without having props for all translation strings on a component level. Thoughts? :slightly_smiling_face:

Comment (adrianschmidt) [reply src/components/chip-set/chip-set.tsx:89]: > Is this to make it translatable or do we want consumers to be able to change the label to something completely different?

Ping @Kiarokh ☝️ 

> If it's only for translation purposes, I would suggest to remove this for now and just have it in English. We need to discuss how to handle translations in Lime Elements at a broader scope before it becomes unmaintainable. I would prefer if we could solve it without having props for all translation strings on a component level. Thoughts? 🙂

It seems we already have some temporary hardcoded translations in Lime Elements, used for the date-picker. If it's for translation, I would suggest adding the translations there for now.

I absolutely agree that we should discuss how to handle translations generally 👍

Comment (Kiarokh) [reply src/components/chip-set/chip-set.tsx:89]: > Ping @Kiarokh ☝️ 

thanks

> Is this to make it translatable

yes :) 

> handle translations in Lime Elements at a broader scope

would be awesome, decent, amazing, professional ;) 

> solve it without having props for all translation strings on a component level

you guys know the best how to do it optimally

Comment (adrianschmidt) [reply src/components/chip-set/chip-set.tsx:89]: Great! I'll add some hardcoded translations 👍

Comment (adrianschmidt) [reply src/components/chip-set/chip-set.tsx:89]: Ah, crap… no, that's just going to require us to send in the language code instead. I'm going with English only for now.

Unfortunately, since that property has already been merged and released, this is now becoming a breaking change 😭

Comment (adrianschmidt) [reply src/components/chip-set/chip-set.tsx]: I decided to deprecate the property, and give it a default value in English. That way we can avoid making a breaking change for now.

File: src/components/chip-set/chip-set.tsx [hunk 6]
```diff
@@ -83,10 +83,10 @@ export class ChipSet {
     public searchLabel: string;
 
     /**
-     * Label to display as `title` and `aria-label` for button that clears all chips
+     * ***DEPRECATED*** Label to display as `title` and `aria-label` for button that clears all chips
```
Comment (jgroth) [inline src/components/chip-set/chip-set.tsx:86]:
```suggestion
     * Label to display as `title` and `aria-label` for button that clears all chips
     * @deprecated
```

**Comment by jgroth** [comment]
I'm not sure why GitHub is not letting me respond in the thread so I'm forced to write my reply here instead...

> Unfortunately, since that property has already been merged and released, this is now becoming a breaking change :sob:

Has it been merged? :thinking:  It's part of this PR is it not? I'm confused now :smile:

**Comment by maltja** [comment]
It doesn't seem to work for me to focus on the clear all chips button with tab in Firefox and Safari. Chrome works perfect.

**Comment by adrianschmidt** [comment]
> I'm not sure why GitHub is not letting me respond in the thread so I'm forced to write my reply here instead...
> 
> > Unfortunately, since that property has already been merged and released, this is now becoming a breaking change 😭
> 
> Has it been merged? 🤔 It's part of this PR is it not? I'm confused now 😄

Oh, yeah, it is! I thought it had just been renamed in this one, but introduced in the PR where the button was added. I'll just remove the prop then! 🎉

**Comment by adrianschmidt** [comment]
> It doesn't seem to work for me to focus on the clear all chips button with tab in Firefox and Safari. Chrome works perfect.

Good catch! I'll take a look at it 👍

File: src/components/chip-set/chip-set.tsx (hunk 6 above)
Comment (adrianschmidt) [reply src/components/chip-set/chip-set.tsx]: Resolving this as I removed the property.

File: src/components/chip-set/chip-set.tsx (hunk 5 above)
Comment (adrianschmidt) [reply src/components/chip-set/chip-set.tsx]: Sorry for being confused. The property was introduced in this PR, so I just removed it and used a hardcoded value in English instead.

**Comment by adrianschmidt** [comment]
> > It doesn't seem to work for me to focus on the clear all chips button with tab in Firefox and Safari. Chrome works perfect.
> 
> Good catch! I'll take a look at it 👍

I could get it to work in Firefox if I changed it from an `<a>` to a `<button>`, but then I lost the hover effect. Safari refused to focus it whatever I did, but I think Safari generally doesn't focus on any links or buttons?

I've now spent most of the day on this without really getting anywhere, and I think we should just merge this as it's clearly better than what's currently on master. If we wish to spend more time polishing it later, we can do so in a separate PR.

**Comment by Kiarokh** [comment]
I also think we should merge it. We will at some point go through keyboard navigation and focus styles of all components. These things we can certainly improve later.

However, it might be a good idea to already create an issue regarding Safari in this board https://github.com/orgs/Lundalogik/projects/61 so we don't forget them.

**Comment by adrianschmidt** [comment]
It actually works in Safari, but you have to enable this accessibility option in Safari's preferences:

image

**Review by jgroth — APPROVED** [review]
