### PR TITLE
fix(menu-surface): do not kill click events when clicking in an allowed element

### LINKED ISSUE #1062: limel-picker: Clicking the button to remove all chips when the dropdown is open breaks the picker
## Current behavior

Clicking the x icon to the right (is it even needed at all?) makes it impossible to get the drop down to close again by clicking outside the drop down.

97188322-acbb5b80-17a3-11eb-9f9e-c8604dd008bb

1. In a limel-picker that is configured with `multiple=true`, select one or more items
2. Open the dropdown again (you may have to click outside first, then on the picker again, this is a separate bug: #1064)
3. Hover the remove-button on the right edge of the picker, note that it does indicate that it can be clicked:
   image
   Important! Use the remove-button for removing all chips at once, _not_ the one on the chip itself (see separate bug concerning that one: #1063)
4. Click on the button

- The chips remain in the picker
- The picker is blurred, but the dropdown remains open
- Clicking outside the picker does not close the dropdown
- Clicking on the input does not focus the picker again
- Clicking on the remove button of a chip does nothing
- Clicking on the remove-all button does nothing
- At this point, there is only one way to close the picker: you have to select an item in the dropdown, once you do, the picker works as normal again

## Expected behavior

- All chips should be removed
- Ideally, if the chips are removed when the picker is open, it should stay open, and if the chips are removed when the picker is closed, it should probably stay closed… if that can't be achieved, I'm not sure which is better, always closing it or always opening it…? /@adrianschmidt

## Environment

- **lime-elements** version: 29.7.1
- Framework used: Can be reproduced in the docs

### PR DESCRIPTION
**Pull request by hannahu**
fix #1062

## Review:
- [ ] Commits are [atomic](https://seesparkbox.com/foundry/atomic_commits_with_git)
- [ ] Commits have the correct *type* for the changes made
- [ ] Commits with *breaking changes* are marked as such

### Browsers tested:
(Check any that applies, it's ok to leave boxes unchecked if testing something didn't seem relevant.)

Windows:
- [ ] Chrome
- [ ] Edge
- [ ] Firefox

Linux:
- [ ] Chrome
- [ ] Firefox

macOS:
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

Mobile:
- [ ] Chrome on Android
- [ ] iOS

### CODE REVIEW

File: src/components/menu-surface/menu-surface.tsx [hunk 1]
```diff
@@ -106,12 +112,32 @@ export class MenuSurface {
     }
 
     private handleDocumentClick(event) {
-        if (this.open && !isDescendant(event.target, this.host)) {
+        const elementPath = event.path || [];
+
+        const clickedInAllowedElement = this.isElementInPath(
+            elementPath,
+            this.allowClicksElement
```
Comment (adrianschmidt) [inline src/components/menu-surface/menu-surface.tsx:119]: Awesome! This was the once thing I had a comment about when I looked it over earlier, because a click in any _other_ picker would have also been allowed to propagate, and wouldn't close the picker 👍

Comment (adrianschmidt) [reply src/components/menu-surface/menu-surface.tsx:119]: Tiny question though: Rather than looking at the path, can't we use `isDescendant` for this check as well?

Comment (adrianschmidt) [reply src/components/menu-surface/menu-surface.tsx:119]:
```tsx
isDescendant(event.target, this.allowClicksElement);
```

Comment (hannahu) [reply src/components/menu-surface/menu-surface.tsx:119]: Then we can't know which element that was clicked since the event.target is the document?

Comment (adrianschmidt) [reply src/components/menu-surface/menu-surface.tsx:119]: Hmm… I'm pretty sure event.target should still be the element that was clicked, not the element on which the handler was registered…? Are you sure? 🤔

Comment (hannahu) [reply src/components/menu-surface/menu-surface.tsx:119]: Yes since it's shadow doms! :/

Comment (adrianschmidt) [reply src/components/menu-surface/menu-surface.tsx:119]: Whaa… really? Now I'm confused and curious! 😄

Imma fiddle around a bit, and see if I can understand what's happening… 🤔

Comment (adrianschmidt) [reply src/components/menu-surface/menu-surface.tsx:119]: Wow, yeah, you're absolutely right 👍

Good thing I found out about that little quirk before it bit me! 🙏

File: src/components/menu-surface/menu-surface.tsx [hunk 2]
```diff
@@ -106,12 +112,32 @@ export class MenuSurface {
     }
 
     private handleDocumentClick(event) {
-        if (this.open && !isDescendant(event.target, this.host)) {
+        const elementPath = event.path || [];
+
+        const clickedInAllowedElement = this.isElementInPath(
```
Comment (adrianschmidt) [inline src/components/menu-surface/menu-surface.tsx:117]: We want to check `this.open` before we do this. At the moment, each menu-surface loops through the path for every single click, even when no surface-area is open. In the docs for `limel-select`, that's 10 times for each click 😅

We should also check if `this.allowClicksElement` is even truthy before we run this. If it's not, there's no reason to do the loop at all.

Comment (jgroth) [reply src/components/menu-surface/menu-surface.tsx:117]: I think we could also replace our own private method with something like t his :thinking: 
```ts
const clickedInAllowedElement = elementPath.includes(this.allowClicksElement);
```

File: src/components/menu-surface/menu-surface.tsx [hunk 3]
```diff
@@ -31,6 +31,12 @@ export class MenuSurface {
     @Prop()
     public open = false;
 
+    /**
+     * Clicks in this element should not be prevented
```
Comment (jgroth) [inline src/components/menu-surface/menu-surface.tsx:35]:
```suggestion
     * Clicks in this element should not be prevented when the menu surface is open
```

File: src/components/menu-surface/menu-surface.tsx (hunk 2 above)
Comment (hannahu) [reply src/components/menu-surface/menu-surface.tsx:117]: > I think we could also replace our own private method with something like this 
> 
> ```ts
> const clickedInAllowedElement = elementPath.includes(this.allowClicksElement);
> ```

ah yeah now we can do that!

Comment (hannahu) [reply src/components/menu-surface/menu-surface.tsx:117]: > We want to check `this.open` before we do this. At the moment, each menu-surface loops through the path for every single click, even when no surface-area is open. In the docs for `limel-select`, that's 10 times for each click 
> 
> We should also check if `this.allowClicksElement` is even truthy before we run this. If it's not, there's no reason to do the loop at all.

I love loops!!!

File: src/components/menu-surface/menu-surface.tsx [hunk 4]
```diff
@@ -106,7 +112,23 @@ export class MenuSurface {
...
     private handleDocumentClick(event) {
-        if (this.open && !isDescendant(event.target, this.host)) {
+        const elementPath = event.path || [];
+
+        if (!this.open) {
+            return;
+        }
+
+        if (this.allowClicksElement) {
+            const clickedInAllowedElement = elementPath.includes(
```
Comment (hannahu) [inline src/components/menu-surface/menu-surface.tsx:122]: Fixup now done.
I know this row can be put in 121 as well but I think it's easier to follow what happens if we name the result here?
