### PR TITLE
fix(input): cursor jumps to end of input when rapidly typing

### LINKED ISSUE #1255: Limel input: Text cursor jumps to end of input when rapidly typing
## Current behavior

When adding text in the middle of an existing string in the input field the cursor sometimes jumps to the end of the input.
This seems to happen when rapidly typing.

This behaviour is reproducable in the live docs, but also locally.

1. Add some text to an input field
2. Place the cursor at the beginning or middle of the text
3. Type really fast
4. Cursor will randomly jump to end of text

## Expected behavior
The cursor should not move unexpectedly.

## Environment

- **lime-elements** version: 31.10.0
- Framework used: StencilJS

### PR DESCRIPTION
**Pull request by jensgustafsson**
When adding text in the middle of an existing string in the input field the cursor sometimes jumps
to the end of the input.

fix #1255

## Review:
- [x] Commits are [atomic](https://seesparkbox.com/foundry/atomic_commits_with_git)
- [x] Commits have the correct *type* for the changes made
- [x] Commits with *breaking changes* are marked as such

### Browsers tested:
(Check any that applies, it's ok to leave boxes unchecked if testing something didn't seem relevant.)

Windows:
- [x] Chrome
- [x] Edge
- [ ] Firefox

Linux:
- [ ] Chrome
- [ ] Firefox

macOS:
- [x] Chrome
- [ ] Firefox
- [ ] Safari

Mobile:
- [ ] Chrome on Android
- [ ] iOS

### CODE REVIEW

File: src/components/input-field/input-field.tsx [hunk 1]
```diff
@@ -235,12 +235,8 @@ export class InputField {
         this.handleCloseMenu = this.handleCloseMenu.bind(this);
         this.setFocus = this.setFocus.bind(this);
 
-        const debounceTimeout = 100;
-        this.changeEmitter = debounce(this.changeEmitter, debounceTimeout, {
-            leading: false,
-            maxWait: 300,
-            trailing: true,
-        });
```
Comment (jensgustafsson) [inline src/components/input-field/input-field.tsx:243]: I was able to "solve this" (not being able to repro it anymore) by removing the `maxWait` time and changing the debounce timeout to 300.

The default values for `leading` and `trailing` is already set to `false` and `true`, thus the whole config object was removed.

Comment (adrianschmidt) [reply src/components/input-field/input-field.tsx:243]: Nice!

I'll have my best go at "breaking" it while testing 😝

**Review by adrianschmidt — APPROVED** [review]
