### PR TITLE
fix(date-picker): improve handling of focus on the input field

### LINKED ISSUE #764: Focus on datepicker
## Current behavior

The first time I pick a date it gets marked with the green colour which stays even when I go to another field. In the picture below I first picked a date and then I choose "Sales Status" and then both got marked.

If I go back to the datepicker and then to a new field the colour goes away but not the first time.

image

## Expected behavior

that it gets grey, when leaving to another field

## Environment

- **lime-elements** version: 22.3.0

### PR DESCRIPTION
**Pull request by jensgustafsson**
This commit ensures that the input element has focus when the datepicker closes. It also fixes a bug
where it could look like several input fields had focus at the same time.

fix #764

## Review:
- [ ] Commits are [atomic](https://seesparkbox.com/foundry/atomic_commits_with_git)
- [ ] Commits have the correct *type* for the changes made
- [ ] Commits with *breaking changes* are marked as such

### Browsers tested:
(Check any that applies, it's ok to leave boxes unchecked if testing something didn't seem relevant.)

Windows:
- [ ] Chrome
- [ ] Edge
- [ ] Firefox

Linux:
- [ ] Chrome
- [ ] Firefox

macOS:
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

Mobile:
- [ ] Chrome on Android
- [ ] iOS

### CODE REVIEW

File: src/components/date-picker/date-picker.tsx [hunk 1]
```diff
@@ -284,7 +285,6 @@ export class DatePicker {
         );
         event.stopPropagation();
         if (this.type !== 'datetime' && this.type !== 'time') {
-            this.textField.blur();
```
Comment (jensgustafsson) [inline src/components/date-picker/date-picker.tsx:287]: This had no effect as the textfield is not an input field but a limel-input-field.

File: src/components/date-picker/date-picker.tsx [hunk 2]
```diff
@@ -259,6 +259,7 @@ export class DatePicker {
         setTimeout(() => {
             this.showPortal = false;
         });
+        this.textField.shadowRoot.querySelector('input').focus();
```
Comment (jensgustafsson) [inline src/components/date-picker/date-picker.tsx:262]: this fixes the bug Sofie mentioned in #764. It also makes our tabbing work better as we no longer have focus on the root dom element after the datepicker has closed

Comment (adrianschmidt) [reply src/components/date-picker/date-picker.tsx:262]: Looks good. Since we do it in `hideCalendar`, I assume this doesn't mean we set focus immediately on creation, but please make sure to check that @BregenzerK.
